FROM python:3.11-slim

WORKDIR /app

COPY requirements.dash.txt .
RUN pip install --no-cache-dir -r requirements.dash.txt

COPY dashboard/ ./dashboard/

EXPOSE 8050

CMD ["python", "dashboard/app.py"]